server:
  port: 23333

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      table-prefix: b_
  mapper-locations: classpath*:mapper/*.xml



spring:
  datasource:
    url: jdbc:mysql://localhost:3306/newblog?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: blog
    password: 123456

    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      validation-query: select 'x'
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat, wall
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      use-global-data-source-stat: true

      ## StatViewServlet配置，说明请参考Druid Wiki，配置_StatViewServlet配置
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        allow: 127.0.0.1
        login-password: 123456
        login-username: admin

      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"

      filter:
        wall:
          enabled: true
          db-type: mysql
          config:
            alter-table-allow: false
            truncate-allow: false
            drop-table-allow: false


logging:
  group:
    tomcat: org.apache.catalina, org.apache.coyote, org.apache.tomcat
  level:
    tomcat: info
    org.springframework: info
    com.ningmeng.vueblog.mapper: debug
    com.ningmeng: info

