background:
  url: https://cn.bing.com/HPImageArchive.aspx?format=js&idx=0&n=1&mkt=zh-CN
  location:
    - /home/ningmengmao/Pictures/
    - /media/ningmengmao/repository/code/git/vue_demo2/static/images/

upload-image-path: /media/ningmengmao/repository/code/git/vue_demo2/static/images/
index-path: http://localhost:8080/

github:
  client_id: 0e6e75e59c17d0598778
  client_secret: bcea39e82b5347913962c1496a6b432368876e53
  redirect_url: http://localhost:23333/api/githubCallback
  github_Auth_url: https://github.com/login/oauth/authorize?client_id=0e6e75e59c17d0598778&redirect_uri=http://localhost:23333/api/githubCallback&scope=user&state=1

baidu:
  id: 17606837
  api-key: Okjx7mzOlwiD8qM6ELiwK1Kq
  secret-key: fwIUulOZminM5oSxNLMVlm81QYU7fqOg

audience:
  client-id: 370c4202ed9c460194e72e11255f4045a8b04b31a9284a0aa676752b6a6154d85213d5b889e24896b3aec009b6a8164a8be3b719a7324eef8b067d5c89eb406b581a60f9c4564b53bf572c86041e3448a26223e40abf4013adb7d06c2802ee6a6bc9eed043a64b1b9a28d863588df815f4c9748d73864696af79a9b1539e250a
  base64Secret: MzcwYzQyMDJlZDljNDYwMTk0ZTcyZTExMjU1ZjQwNDVhOGIwNGIzMWE5Mjg0YTBhYTY3Njc1MmI2YTYxNTRkODUyMTNkNWI4ODllMjQ4OTZiM2FlYzAwOWI2YTgxNjRhOGJlM2I3MTlhNzMyNGVlZjhiMDY3ZDVjODllYjQwNmI1ODFhNjBmOWM0NTY0YjUzYmY1NzJjODYwNDFlMzQ0OGEyNjIyM2U0MGFiZjQwMTNhZGI3ZDA2YzI4MDJlZTZhNmJjOWVlZDA0M2E2NGIxYjlhMjhkODYzNTg4ZGY4MTVmNGM5NzQ4ZDczODY0Njk2YWY3OWE5YjE1MzllMjUwYQ==
  name: vue-blog
  expiresSecond: 7200

server:
  port: 23333

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      table-prefix: b_
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/newblog?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: blog
    password: 123456

    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      validation-query: select 'x'
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat, wall
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      use-global-data-source-stat: true

      ## StatViewServlet配置，说明请参考Druid Wiki，配置_StatViewServlet配置
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        allow: 127.0.0.1
        login-password: 123456
        login-username: admin

      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"

      filter:
        wall:
          enabled: true
          db-type: mysql
          config:
            alter-table-allow: false
            truncate-allow: false
            drop-table-allow: false
      connection-init-sqls: set names utf8mb4;
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 20MB


logging:
  group:
    tomcat: org.apache.catalina, org.apache.coyote, org.apache.tomcat
  level:
    tomcat: info
    com.baomidou.mybatisplus: debug
    com.ningmeng.vueblog.mapper: debug
    com.ningmeng.vueblog.service: debug
    com.ningmeng.vueblog.controller: debug
    org.springframework.web: debug
  file: log/vue-blog.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSSS} --- {%thread} --- %-5level --- %logger{50} --- %msg%n"

